version: "3.9"

services:
  gemma4:
    build: .
    container_name: gemma4
    ports:
      - "8080:80"
    volumes:
      - ./.db:/workspace/db
      - ./pdfs:/workspace/pdfs
      - ./code:/workspace/code
      - ./.ollama:/workspace/ollama
    environment:
      - LOAD_PDFS=false
    restart: unless-stopped
