version: "3.9"

services:
  gemma4:
    build: .
    container_name: gemma4
    ports:
      - "8080:80"
    volumes:
      - ./db:/workspace/.db
      - ./ollama:/root/.ollama
      - ./pdfs:/workspace/pdfs
      - ./code:/workspace/code
    environment:
      - LOAD_PDFS=false
    restart: unless-stopped
